# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwgrjCkojz3aSruJ2FlyK2k-4sHY1rf7
"""

import pandas as pd

df = pd.read_csv('data.csv')

"""PROMEDIO"""

promedio_edad = df['Age'].mean()
promedio_edad

"""VALORES NULOS"""

valores_nulos_por_columna = df.isnull().sum()
valores_nulos_por_columna

"""GENERO MAS REPETIDO"""

genero_mas_repetido =df['Gender'].mode()
genero_mas_repetido

"""CANTIDAD HOMBRES"""

hombres = (df['Gender']==0).sum()
hombres

"""CANTIDAD DE MUJERS"""

mujeres=(df['Gender']==1).sum()
mujeres

"""ESTUDIANTES DEPORTISTAS"""

estudiantes_deportistas=(df['Sports']==1).sum()
estudiantes_deportistas

"""ESTUDIANTES DEPORTISTAS POR GENERO

CANTIDAD DE PERSONAS QUE VAN A TUTORIAS
"""

TUTORAS=(df['Tutoring']==1).sum()
TUTORAS

"""CANTIDAD DE PERSONAS QUE VAN A TUTORIAS POR GENERO"""

df.groupby(by=['Gender']).sum( )

"""TIEMPO DE ESTUDIO MAX Y MIN POR SEMANA"""

tiempo_estudio_max=df['StudyTimeWeekly'].max()
tiempo_estudio_max

tiempo_estudio_min=df['StudyTimeWeekly'].min()
tiempo_estudio_min